#!/bin/sh
lib=`pwd`/include
mv stalin-cosmo $lib
(echo "#!/bin/sh"; echo "exec $lib/stalin-cosmo -I $lib -copt -fno-strict-aliasing "'$@') >stalin-cosmo
chmod a+x stalin-cosmo
ln -sf stalin-cosmo stalin
