#!/bin/sh
case `uname -m`/`uname -s` in
  i[3456]86/*)
    echo "IA32";;
  x86_64/*|amd64/*)
    echo "AMD64";;
  aarch64/*|arm64/*)
    echo "IA32";;  # Workaround: Use IA32 for ARM64 hosts (Stalin doesn't know ARM64)
  sparc/Linux)
    echo "SPARC";;
  sparc64/Linux)
    echo "SPARC64";;
  sun4*/*)
    echo "SPARC";;
  IP*/IRIX*)
    echo "MIPS";;
  alpha/*)
    echo "Alpha";;
  arm*/*)
    echo "ARM";;
  m68k/Linux)
    echo "M68K";;
  "Power Macintosh/Darwin")
    echo "PowerPC";;
  powerpc64/*|ppc64/*)
    echo "PowerPC64";;
  s390/Linux)
    echo "S390";;
  000661704C00/AIX)
    echo "PowerPC64";;
  000661714C00/AIX)
    echo "PowerPC64";;
  000661724C00/AIX)
    echo "PowerPC64";;
  000661734C00/AIX)
    echo "PowerPC64";;
  *)
    # For Cosmopolitan builds, default to IA32 as universal bootstrap
    echo "IA32";;
  esac
